In [1]:
import pandas as pd

In [ ]:
#data manupulation cleaning and analysis

#series = one d labeld array
#dataframe = a 2d labeled table

s = pd.Series([10,20,30,40])
print(s) #auto indexing

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
s = pd.Series([10,20,30,40] , index = ["harry" , "vabhav", "sejal" , "sneha"])
print(s) #custom index

harry     10
vabhav    20
sejal     30
sneha     40
dtype: int64

In [4]:
#data frame = dict of series

data = {
    "name": ["Alice", "Bob", "Charlie"],
    "age": [25, 30, 35],
    "city": ["Delhi", "Mumbai", "Bangalore"]
}

df = pd.DataFrame(data)
print(df)

      name  age       city
0    Alice   25      Delhi
1      Bob   30     Mumbai
2  Charlie   35  Bangalore

In [5]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [6]:
df.columns

Index(['name', 'age', 'city'], dtype='object')

In [7]:
# Most Pandas operations are built on these foundations:

# Selection
# Filtering
# Merging
# Aggregation

In [8]:
# creating dataframe

import numpy as np

In [9]:
data = [['harry',24],['jack',45],['jill',46],['jaa',49]]

In [10]:
data

[['harry', 24], ['jack', 45], ['jill', 46], ['jaa', 49]]

In [11]:
pd.DataFrame(data, columns=['name', 'marks'])

    name  marks
0  harry     24
1   jack     45
2   jill     46
3    jaa     49

In [12]:
#now by numpy

arr =np.array([[1,2],[4,5]])

df = pd.DataFrame(arr,columns=["A",'B'])

In [13]:
df

   A  B
0  1  2
1  4  5

In [15]:
# reading through excel
df = pd.read_excel("data.xlsx")
df

      name school   marks
0  viabhav     lps      66
1    tarun     sps      78
2   vibhav     dps      54
3   tarrak      kv      78
4    rahul     lps      34
5    sneha     lsp      45
6  geetika     lps      67

In [16]:
pd.read_json("data.json")

      name    lang
0  vaibhav  python
1  geetika  python

In [ ]:
#read from web
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
df

#below are the eda

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [28]:
df.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [29]:
df.tail(5)

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [31]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [33]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [34]:
df.shape

(244, 7)

In [35]:
selected_column = df[["total_bill" , "tip"]]
selected_column

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [49]:
filterd_row = df[(df["total_bill"]>50.0)]
filterd_row

     total_bill   tip   sex smoker  day    time  size
170       50.81  10.0  Male    Yes  Sat  Dinner     3

In [46]:
filterd_row = df.to_csv("filted.csv",index=False)