In [1]:
import pandas as pd

In [2]:
#handle missing data 
# drop the mising value
#filling the missing value
# interpolation = baesd on data we cna fill

In [ ]:

# df = df.dropna()

# df = df.dropna(axis = 1)

# df["salary"] = df["salary"].fillna(0)

# #interpolation

# df["comun_name"] = df["column_name"].interpilate()

# #rename
# df = df.rename(columns={"old":"new"})
# astype = datatype

# df["new_column"] = df["existing_column"]*2

In [4]:
import numpy as np

In [20]:
data = {
    "name":["alice","bob", np.nan , "david"],
    "age" : [25,np.nan,34,66],
    "score" : [45,67,np.nan,66]
}

In [21]:
df = pd.DataFrame(data)
df

    name   age  score
0  alice  25.0   45.0
1    bob   NaN   67.0
2    NaN  34.0    NaN
3  david  66.0   66.0

In [22]:
df["age"] = df["age"].fillna(df["age"].mean())
df["score"] = df["score"].interpolate()

In [23]:
df

    name        age  score
0  alice  25.000000   45.0
1    bob  41.666667   67.0
2    NaN  34.000000   66.5
3  david  66.000000   66.0

In [24]:
df = df.rename(columns={"name" : "name_1"})
df

  name_1        age  score
0  alice  25.000000   45.0
1    bob  41.666667   67.0
2    NaN  34.000000   66.5
3  david  66.000000   66.0

In [25]:
data2 = {
    "name_1":["vaibhav","sam", "joe" , "sneha"],
    "age" : [32,33,65,44],
    "score" : [45,63,44,65]
}

In [26]:
pd.DataFrame(data2)

    name_1  age  score
0  vaibhav   32     45
1      sam   33     63
2      joe   65     44
3    sneha   44     65

In [19]:
merged = pd.merge(data,data2)

TypeError: Can only merge Series or DataFrame objects, a <class 'dict'> was passed