In [4]:
import pandas as pd
import matplotlib as mp

In [5]:
#handle missing data 
# drop the mising value
#filling the missing value
# interpolation = baesd on data we cna fill

In [6]:

# df = df.dropna()

# df = df.dropna(axis = 1)

# df["salary"] = df["salary"].fillna(0)

# #interpolation

# df["comun_name"] = df["column_name"].interpilate()

# #rename
# df = df.rename(columns={"old":"new"})
# astype = datatype

# df["new_column"] = df["existing_column"]*2

In [7]:
import numpy as np

In [8]:
data = {
    "id":[1,2,3,4],
    "name":["alice","bob", np.nan , "david"],
    "age" : [25,np.nan,34,66],
    "score" : [45,67,np.nan,66]
}

In [9]:
df = pd.DataFrame(data)
df

   id   name   age  score
0   1  alice  25.0   45.0
1   2    bob   NaN   67.0
2   3    NaN  34.0    NaN
3   4  david  66.0   66.0

In [10]:
df["age"] = df["age"].fillna(df["age"].mean())
df["score"] = df["score"].interpolate()

In [11]:
df

   id   name        age  score
0   1  alice  25.000000   45.0
1   2    bob  41.666667   67.0
2   3    NaN  34.000000   66.5
3   4  david  66.000000   66.0

In [12]:
df = df.rename(columns={"name" : "name_1"})
df

   id name_1        age  score
0   1  alice  25.000000   45.0
1   2    bob  41.666667   67.0
2   3    NaN  34.000000   66.5
3   4  david  66.000000   66.0

In [13]:
data2 = {
    "id":[1,2,3,4],
    "name_1":["vaibhav","sam", "joe" , "sneha"],
    "age" : [32,33,65,44],
    "score" : [45,63,44,65]
}

In [14]:
df2 = pd.DataFrame(data2)
df2

   id   name_1  age  score
0   1  vaibhav   32     45
1   2      sam   33     63
2   3      joe   65     44
3   4    sneha   44     65

In [15]:
merged = pd.merge(df,df2,how='inner',on="id")

In [16]:
merged

   id name_1_x      age_x  score_x name_1_y  age_y  score_y
0   1    alice  25.000000     45.0  vaibhav     32       45
1   2      bob  41.666667     67.0      sam     33       63
2   3      NaN  34.000000     66.5      joe     65       44
3   4    david  66.000000     66.0    sneha     44       65